on:
    release:
        types: [published]
name: Deploy Extension
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '20'
            - run: npm install
            - run: npm install -g @vscode/vsce
            - run: vsce package
            - run: vsce publish -p ${{ secrets.AZURE_ACCESS_TOKEN }}
